name: "linux tests and documentation builds for 'kiara_plugin.{{ cookiecutter.project_slug }}'"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:

#  commitlint:
#    name: lint commit message
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: wagoid/commitlint-github-action@v4

  test-linux:
    name: pytest on linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10"]
    steps:
      - name: "Set up Python {% raw %}${{ matrix.python_version }}{% endraw %}"
        uses: actions/setup-python@v2
        with:
          python-version: "{% raw %}${{ matrix.python_version }}{% endraw %}"
      - uses: actions/checkout@v2
      - name: install kiara_plugin.{{ cookiecutter.project_slug }}
        run: pip install -U --pre --extra-index-url https://pypi.fury.io/dharpa/ .[all,dev_testing]
      - name: display installed kiara and module package versions
        run: pip list | grep kiara
      - name: Test with pytest
        run: make test

# Uncomment this if you have coveralls.io setup with this repo
#  coverage:
#    name: create and publish test coverage
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Set up Python 3.9"
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.9
#      - uses: actions/checkout@v2
#      - name: install kiara
#        run: pip install -U --pre --extra-index-url https://pypi.fury.io/dharpa/ .[all,dev_testing]
#      - name: display installed kiara and module package versions
#        run: pip list | grep kiara
#      - name: Run coverage
#        run: coverage run -m pytest tests
#      - name: Upload coverage data to coveralls.io
#        run: coveralls --service=github
#        env:
#          GITHUB_TOKEN:  {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}""

#  mypy-linux:
#    name: mypy check on linux
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python_version: [3.8, 3.9]
#    steps:
#      - name: "Set up Python {% raw %}${{ matrix.python_version }}{% endraw %}"
#        uses: actions/setup-python@v2
#        with:
#          python-version: "{% raw %}${{ matrix.python_version }}{% endraw %}"
#      - uses: actions/checkout@v2
#      - name: install kiara_plugin.{{ cookiecutter.project_slug }}
#        run: pip install -U --pre --extra-index-url https://pypi.fury.io/dharpa/ .[all,dev_testing]
#      - name: Test with mypy
#        run: make mypy

#  flake8-linux:
#    name: flake8 on linux
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up Python 3.9
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.9
#      - uses: actions/checkout@v2
#      - name: install kiara_plugin.{{ cookiecutter.project_slug }}
#        run: pip install -U --pre --extra-index-url https://pypi.fury.io/dharpa/ .[all,dev_testing]
#      - name: Test with flake8
#        run: make flake

  build-docs:
    name: build documentation
    if: {% raw %}${{ github.ref == 'refs/heads/develop' }} || ${{ github.ref == 'refs/heads/main' }} || startsWith(github.ref, 'refs/tags/'){% endraw %}
    runs-on: ubuntu-latest
    needs:
      - test-linux
#      - mypy-linux
#      - flake8-linux
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install kiara_plugin.{{ cookiecutter.project_slug }} develop
        if: {% raw %}${{ ( github.ref == 'refs/heads/develop') }}{% endraw %}
        run: pip install -U --pre --extra-index-url https://pypi.fury.io/dharpa/ .[all,dev_documentation]
      - name: install kiara_plugin.{{ cookiecutter.project_slug }} release
        if: startsWith(github.ref, 'refs/tags')
        run: pip install -U --extra-index-url https://pypi.fury.io/dharpa/ .[all,dev_documentation]
      - run: git config --global user.email "{{ cookiecutter.full_name }}"
      - run: git config --global user.name "{{ cookiecutter.email }}"
      - name: create latest documentation
        if: {% raw %}${{ ( github.ref == 'refs/heads/develop') }}{% endraw %}
        run: FAIL_DOC_BUILD_ON_ERROR=true mike deploy --push latest && mike set-default --push latest
      - name: extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: create stable documentation
        if: startsWith(github.ref, 'refs/tags')
        run: FAIL_DOC_BUILD_ON_ERROR=true mike deploy --push --update-alias --title "v ${RELEASE_VERSION}" "${RELEASE_VERSION}" stable

  release_package:
    name: publish python package
    if: {% raw %}${{ github.ref == 'refs/heads/develop' }} || ${{ github.ref == 'refs/heads/main' }} || startsWith(github.ref, 'refs/tags/'){% endraw %}
    runs-on: ubuntu-latest
    needs:
      - test-linux
#      - mypy-linux
#      - flake8-linux
    env:
        GEMFURY_PUSH_TOKEN: {% raw %}${{ secrets.GEMFURY_PUSH_TOKEN }}{% endraw %}
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install pip
        run: pip install pip==21.2.4 setuptools==57.4.0
      - name: install kiara
        run: pip install -U --extra-index-url https://pypi.fury.io/dharpa/ -e .[all]
      - name: install 'wheel' package
        run: pip install -U wheel
      - name: create packages
        run: python setup.py sdist bdist_wheel
      - name: upload source package
        run: {% raw %}curl -F package=@$(ls dist/kiara*.tar.gz) https://${GEMFURY_PUSH_TOKEN}@dharpa.fury.land:443/pypi/{% endraw %}
      - name: upload wheel
        run: {% raw %}curl -F package=@$(ls dist/kiara*.whl) https://${GEMFURY_PUSH_TOKEN}@dharpa.fury.land:443/pypi/{% endraw %}
      - name: publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: {% raw %}"${{ secrets.PYPI_API_TOKEN }}"{% endraw %}

  test_conda_package_build:
    name: test conda package build
    runs-on: ubuntu-latest
    if: {% raw %}${{ startsWith(github.ref, 'refs/tags') != true }}{% endraw %}
    strategy:
      matrix:
        python_version: ["3.8", "3.9"]   # '3.10' currently does not work, missing vaex conda packages
    steps:
      - uses: actions/checkout@v1
      - uses: conda-incubator/setup-miniconda@v2
      - name: install conda build packages
        run: conda install -c conda-forge conda-build anaconda-client boa
      - name: build conda package
        run: cd ci/conda/ && ./build-conda-packages.sh "kiara_plugin.{{ cookiecutter.project_slug }}" develop {% raw %}"${{ matrix.python_version }}"{% endraw %} true

  publish_conda_package:
    name: publish conda package
    runs-on: ubuntu-latest
    if: {% raw %}${{ startsWith(github.ref, 'refs/tags') }}{% endraw %}
    strategy:
      matrix:
        python_version: ["3.8", "3.9"]   # '3.10' currently does not work, missing vaex conda packages
    env:
      ANACONDA_PUSH_TOKEN: {% raw %}${{ secrets.ANACONDA_PUSH_TOKEN }}{% endraw %}
    needs:
      - test-linux
#      - mypy-linux
#      - flake8-linux
    steps:
      - uses: actions/checkout@v1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: "anaconda-build-env"
      - name: install conda build packages
        run: conda install -c conda-forge -n anaconda-build-env conda-build anaconda-client boa
      - name: build conda package
        shell: bash -l {0}
        run: conda activate anaconda-build-env && cd ci/conda/ && ./build-conda-packages.sh "kiara_plugin.{{ cookiecutter.project_slug }}" "${GITHUB_REF#refs/*/}" {% raw %}"${{ matrix.python_version }}"{% endraw %} false

  merge_tag_to_main:
    name: merge current tag to main branch
    runs-on: ubuntu-latest
    if: {% raw %}${{ startsWith(github.ref, 'refs/tags') }}{% endraw %}
    needs:
      - test-linux
#      - mypy-linux
#      - flake8-linux
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git config --global user.email "markus@frkl.io"
    - run: git config --global user.name "Markus Binsteiner"
    - name: extract tag name
      run: {% raw %}echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV{% endraw %}
    - name: checkout main branch
      run: git checkout main
    - name: merge tag
      run: git merge "${RELEASE_VERSION}"
    - name: push updated main branch
      run: git push https://{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}@github.com/{{ cookiecutter.github_user }}/kiara_plugin.{{ cookiecutter.project_slug }}.git
